[package]
name = "baseless"
version = "0.0.0"
authors = ["Max Bond <max.o.bond@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
